// Define la palabra a adivinar
//const wordToGuess = "HELLO";
const palabras = [
        { palabra: "EXCELENTE", pista: "Sinónimo de sobresaliente" },
        { palabra: "INMORTAL", pista: "Que no puede morir" },
        { palabra: "RELEVANTE", pista: "Importante o significativo" },
        { palabra: "ARQUITECTO", pista: "Diseñador de edificios" },
        { palabra: "MAGNIFICO", pista: "Espléndido o grandioso" },
        { palabra: "PROFESION", pista: "Ocupación u oficio" },
        { palabra: "PLUTOCRACIA", pista: "Gobierno de los ricos" },
        { palabra: "ESOTERICO", pista: "Conocimiento secreto o misterioso" },
        { palabra: "DESPRECIO", pista: "Sentimiento de menosprecio" },
        { palabra: "ELOCUENTE", pista: "Que se expresa con facilidad" },
        { palabra: "SOFISTICADO", pista: "Elegante y complejo" },
        { palabra: "EXPERIMENTO", pista: "Prueba o ensayo científico" },
        { palabra: "DELIBERAR", pista: "Considerar detenidamente" },
        { palabra: "PERSEVERAR", pista: "Persistir en una acción" },
        { palabra: "RECONOCIDO", pista: "Admirado o identificado" },
        { palabra: "ABSTRACCION", pista: "Concepto o idea no concreta" },
        { palabra: "AUTORIDAD", pista: "Poder o dominio" },
        { palabra: "JURISPRUDENCIA", pista: "Estudio del derecho" },
        { palabra: "CONSTITUCION", pista: "Ley fundamental de un país" },
        { palabra: "FUNDAMENTAL", pista: "Esencial o básico" },
        { palabra: "INTELIGENTE", pista: "Persona con capacidad mental" },
        { palabra: "CURIOSIDAD", pista: "Deseo de conocer" },
        { palabra: "HIPOTETICO", pista: "Basado en suposiciones" },
        { palabra: "CONTRADICCION", pista: "Oposición entre ideas" },
        { palabra: "ILUSTRACION", pista: "Época de la razón" },
        { palabra: "ENAMORAMIENTO", pista: "Sentimiento amoroso inicial" },
        { palabra: "FRAGMENTO", pista: "Parte separada de un todo" },
        { palabra: "CONTEMPLAR", pista: "Observar con atención" },
        { palabra: "INTANGIBLE", pista: "Que no se puede tocar" },
        { palabra: "ABUNDANTE", pista: "En gran cantidad" },
        { palabra: "PROMINENTE", pista: "Destacado o sobresaliente" },
        { palabra: "TOLERANCIA", pista: "Respeto hacia las diferencias" },
        { palabra: "CIRCUNFERENCIA", pista: "Línea que rodea un círculo" },
        { palabra: "DELINCUENTE", pista: "Criminal o infractor" },
        { palabra: "CONVERGENCIA", pista: "Acercamiento de ideas" },
        { palabra: "PERSPICAZ", pista: "Agudo en la observación" },
        { palabra: "PARADOJA", pista: "Contradicción aparente" },
        { palabra: "TRANSCENDENTE", pista: "Importante y profundo" },
        { palabra: "ABUNDANCIA", pista: "Gran cantidad de algo" },
        { palabra: "AMBIGUO", pista: "Que tiene varios significados" },
        { palabra: "DECADENCIA", pista: "Declive o deterioro" },
        { palabra: "PRODIGIOSO", pista: "Extraordinario o asombroso" },
        { palabra: "CONSCIENTE", pista: "Que tiene conocimiento" },
        { palabra: "VULNERABLE", pista: "Susceptible de ser herido" },
        { palabra: "HETEROGENEO", pista: "Diverso o variado" },
        { palabra: "TRASCENDENTAL", pista: "De gran importancia" },
        { palabra: "CONTUNDENTE", pista: "Que convence con fuerza" },
        { palabra: "PRESTIGIO", pista: "Reconocimiento y respeto" },
        { palabra: "ESPECTACULO", pista: "Show o presentación" },
        { palabra: "ASTRONOMIA", pista: "Ciencia de los astros" },
        { palabra: "HALLAZGO", pista: "Descubrimiento importante" },
        { palabra: "CONSECUENTE", pista: "Que tiene lógica" },
        { palabra: "PERSISTENTE", pista: "Que no se rinde" },
        { palabra: "DIVERSIDAD", pista: "Variedad de cosas" },
        { palabra: "INTENCIONAL", pista: "Hecho a propósito" },
        { palabra: "PROPORCION", pista: "Relación entre partes" },
        { palabra: "INVOLUCRADO", pista: "Comprometido en algo" },
        { palabra: "DESCONOCIDO", pista: "Que no se sabe quién es" },
        { palabra: "INCORPORAR", pista: "Agregar o incluir" },
        { palabra: "EQUILIBRIO", pista: "Armonía y estabilidad" },
        { palabra: "DISCRECION", pista: "Cautela y reserva" },
        { palabra: "DISCREPANCIA", pista: "Desacuerdo o diferencia" },
        { palabra: "ENFRENTAR", pista: "Hacer frente a algo" },
        { palabra: "AUTORITARIO", pista: "Que impone su autoridad" },
        { palabra: "INDISPENSABLE", pista: "Necesario e imprescindible" },
        { palabra: "TRANSCURRIR", pista: "Pasar el tiempo" },
        { palabra: "COOPERACION", pista: "Trabajo conjunto" },
        { palabra: "SUPERFICIAL", pista: "Superficialidad" },
        { palabra: "POTENCIAL", pista: "Capacidad para desarrollarse" },
        { palabra: "RELEVANCIA", pista: "Importancia o relevancia" },
        { palabra: "DICTADURA", pista: "Gobierno autoritario" },
        { palabra: "JURAMENTO", pista: "Promesa solemne" },
        { palabra: "MISTERIOSO", pista: "Que es un enigma" },
        { palabra: "ESPIRITUAL", pista: "Relacionado con el espíritu" },
        { palabra: "RESERVADO", pista: "Que guarda secretos" },
        { palabra: "CONTINENTE", pista: "Gran masa de tierra" },
        { palabra: "INDEPENDIENTE", pista: "Libre y autónomo" },
        { palabra: "DOMINANTE", pista: "Que domina o controla" },
        { palabra: "INOCENTE", pista: "Que no es culpable" },
        { palabra: "ILUMINACION", pista: "Luz brillante" },
        { palabra: "REDONDEZ", pista: "Calidad de ser redondo" },
        { palabra: "PRODUCTIVO", pista: "Que produce resultados" },
        { palabra: "INSTITUCION", pista: "Organización formal" },
        { palabra: "CONTAMINACION", pista: "Polución o impureza" },
        { palabra: "FUNDAMENTO", pista: "Base o principio" },
        { palabra: "CONTRADICCION", pista: "Oposición entre ideas" },
        { palabra: "PRESTIGIOSO", pista: "Reconocido y respetado" },
        { palabra: "COMPRENSION", pista: "Entender algo" },
        { palabra: "INSPIRACION", pista: "Estímulo creativo" },
        { palabra: "ATMOSFERA", pista: "Capa de gases alrededor de la Tierra" },
        { palabra: "MISTERIOSO", pista: "Enigmático" },
        { palabra: "ORQUESTA", pista: "Grupo musical" },
        { palabra: "DISCRIMINACION", pista: "Trato injusto" },
        { palabra: "SUPERVIVENCIA", pista: "Permanecer con vida" },
        { palabra: "INNOVACION", pista: "Introducción de novedades" },
        { palabra: "LIBERTAD", pista: "Derecho de elegir" },
        { palabra: "DETERMINACION", pista: "Decisión firme" },
        { palabra: "ALQUIMISTA", pista: "Busca transformar metales" },
        { palabra: "ESPECIALIDAD", pista: "Área de conocimiento" },
        { palabra: "INVESTIGACION", pista: "Búsqueda de información" },
        { palabra: "CONSCIENTEMENTE", pista: "De manera deliberada" },
        { palabra: "DOMINANCIA", pista: "Control o supremacía" },
        { palabra: "DETERMINADO", pista: "Específico o definido" },
        { palabra: "RECOPILACION", pista: "Reunión de datos" },
        { palabra: "BIOLOGIA", pista: "Ciencia de la vida" },
        { palabra: "UNIVERSIDAD", pista: "Institución educativa" },
        { palabra: "ACADEMIA", pista: "Institución educativa" },
        { palabra: "CIVILIZACION", pista: "Sociedad avanzada" },
        { palabra: "COMPLICADO", pista: "Difícil de entender" },
        { palabra: "INVESTIGADOR", pista: "Persona que investiga" },
        { palabra: "ENIGMATICO", pista: "Misterioso o enigmático" },
        { palabra: "EXPERIMENTAL", pista: "Relativo a experimentos" },
        { palabra: "DETERIORO", pista: "Desgaste o deterioro" },
        { palabra: "ENRIQUECEDOR", pista: "Que enriquece" },
        { palabra: "INTRODUCCION", pista: "Inicio o presentación" },
        { palabra: "ORGANIZACION", pista: "Grupo ordenado" },
        { palabra: "DEMOCRACIA", pista: "Sistema de gobierno" },
        { palabra: "MULTIFACETICO", pista: "Con muchas facetas" },
        { palabra: "CONSTANTINOPLA", pista: "Antigua ciudad" },
        { palabra: "CONFRONTACION", pista: "Enfrentamiento" },
        { palabra: "COMPRENSION", pista: "Entendimiento" },
        { palabra: "DETERIORAR", pista: "Hacer que algo empeore" },
        { palabra: "INFLUENCIA", pista: "Poder de afectar" },
        { palabra: "SUBLIME", pista: "Muy hermoso o grandioso" },
        { palabra: "SABIDURIA", pista: "Conocimiento profundo" },
        { palabra: "ABUNDANCIA", pista: "Gran cantidad" },
        { palabra: "FUNDAMENTAL", pista: "Esencial" },
        { palabra: "CONTINUIDAD", pista: "Persistencia en el tiempo" },
        { palabra: "ESPECTADOR", pista: "Persona que mira" },
        { palabra: "INVOLUCRAMIENTO", pista: "Participación activa" },
        { palabra: "CONVIVENCIA", pista: "Vivir juntos" },
        { palabra: "RECONOCIMIENTO", pista: "Admiración o agradecimiento" },
        { palabra: "SATISFACCION", pista: "Sentimiento de contento" },
        { palabra: "IMPRESIONANTE", pista: "Causa impresión" },
        { palabra: "ESFUERZO", pista: "Trabajo duro" },
        { palabra: "INTELIGENCIA", pista: "Capacidad mental" },
        { palabra: "PROSPERIDAD", pista: "Éxito y bienestar" },
        { palabra: "PRINCIPIANTE", pista: "Persona que comienza" },
        { palabra: "CONTRADICTORIO", pista: "Opuesto o contrario" },
        { palabra: "ILUMINADO", pista: "Que ha alcanzado la iluminación" },
        { palabra: "REPRESENTACION", pista: "Acto de representar" },
        { palabra: "ESTABLECIDO", pista: "Estable o fijo" },
        { palabra: "FRUSTRACION", pista: "Sentimiento de fracaso" },
        { palabra: "DETERMINACION", pista: "Decisión firme" },
        { palabra: "EXCELENCIA", pista: "Calidad superior" },
        { palabra: "SENSIBILIDAD", pista: "Capacidad de sentir" },
        { palabra: "COLABORACION", pista: "Trabajo en equipo" },
        { palabra: "INDIFERENCIA", pista: "Falta de interés" },
        { palabra: "INCONFORMIDAD", pista: "Descontento" },
        { palabra: "PERSISTENCIA", pista: "Continuidad en una acción" },
        { palabra: "COMPETITIVO", pista: "Que compite" },
        { palabra: "INTOLERANCIA", pista: "Falta de tolerancia" },
        { palabra: "INVESTIGACION", pista: "Búsqueda de conocimiento" },
        { palabra: "RESPONSABILIDAD", pista: "Deber o carga" },
        { palabra: "PERSISTENTE", pista: "Que no se rinde" },
        { palabra: "CONTINENTAL", pista: "Relacionado con continentes" },
        { palabra: "EXPLORACION", pista: "Acción de explorar" },
        { palabra: "ACADEMIA", pista: "Institución educativa" },
        { palabra: "SUSTENTABILIDAD", pista: "Capacidad de mantenerse" },
        { palabra: "INDEPENDIENTEMENTE", pista: "Sin depender de otros" },
        { palabra: "BIOLOGIA", pista: "Ciencia de la vida" },
        { palabra: "APRENDIZAJE", pista: "Proceso de aprender" },
        { palabra: "COMPRENDER", pista: "Entender algo" },
        { palabra: "DIVERSIFICACION", pista: "Variación o ampliación" },
        { palabra: "INMIGRACION", pista: "Migración a otro país" },
        { palabra: "CONTRADICCION", pista: "Oposición entre ideas" },
        { palabra: "DETERIORO", pista: "Desgaste o debilitamiento" },
        { palabra: "ESTRATEGICO", pista: "Relacionado con estrategias" },
        { palabra: "HUMANIDAD", pista: "Cualidades humanas" },
        { palabra: "PRESTIGIO", pista: "Reconocimiento y respeto" },
        { palabra: "VERSATILIDAD", pista: "Capacidad de adaptarse" },
        { palabra: "INTERESANTE", pista: "Que despierta interés" },
        { palabra: "CREATIVIDAD", pista: "Facultad de crear" },
        { palabra: "HERMOSURA", pista: "Belleza o atractivo" },
        { palabra: "ENAMORAMIENTO", pista: "Sentimiento amoroso inicial" },
        { palabra: "PREDECIR", pista: "Adivinar el futuro" },
        { palabra: "INFINITO", pista: "Ilimitado o eterno" },
        { palabra: "MAGNIFICENCIA", pista: "Esplendor o grandeza" },
        { palabra: "INTERACCION", pista: "Acción de interactuar" },
        { palabra: "POTENCIAL", pista: "Capacidad para desarrollarse" },
        { palabra: "PROFUNDIDAD", pista: "Grandeza o profundidad" },
        { palabra: "FENOMENAL", pista: "Extraordinario o asombroso" },
        { palabra: "ESTABLECIMIENTO", pista: "Lugar de negocio" },
        { palabra: "LITERATURA", pista: "Obra escrita" },
        { palabra: "INMENSIDAD", pista: "Grandeza infinita" },
        { palabra: "PERSISTENTE", pista: "Que no se rinde" },
        { palabra: "DIFERENCIACION", pista: "Distinguir de otros" },
        { palabra: "SOLIDARIDAD", pista: "Unión y apoyo" },
        { palabra: "CONTRASTAR", pista: "Comparar diferencias" },
        { palabra: "INTERCULTURAL", pista: "Entre diferentes culturas" },
        { palabra: "GENEROSIDAD", pista: "Dar sin esperar" },
        { palabra: "HORIZONTE", pista: "Línea que separa cielo y tierra" },
        { palabra: "INCORPORACION", pista: "Inclusión" },
        { palabra: "IDENTIFICACION", pista: "Reconocer algo o alguien" },
        { palabra: "BIOGRAFIA", pista: "Historia de una persona" },
        { palabra: "INTELIGENTE", pista: "Persona con capacidad mental" },
        { palabra: "CULTIVADO", pista: "Educado y refinado" },
        { palabra: "IMAGINACION", pista: "Facultad de crear imágenes" },
        { palabra: "CONFIDENCIAL", pista: "Secreto o privado" },
        { palabra: "IMPRESCINDIBLE", pista: "Necesario e indispensable" },
        { palabra: "IMPLACABLE", pista: "Que no perdona" },
        { palabra: "REPERCUSION", pista: "Impacto o consecuencia" },
        { palabra: "HERMOSURA", pista: "Belleza" },
        { palabra: "AVENTURERO", pista: "Persona que busca aventuras" },
        { palabra: "INTROVERTIDO", pista: "Persona reservada" },
        { palabra: "CONTEMPLACION", pista: "Observación con atención" },
        { palabra: "EXTRAORDINARIO", pista: "Fuera de lo común" },
        { palabra: "IMAGINATIVO", pista: "Creativo y fantasioso" },
        { palabra: "DETERMINADO", pista: "Decidido y enfocado" },
        { palabra: "COMPASION", pista: "Sentimiento de empatía" },
        { palabra: "COMPRENSIBLE", pista: "Fácil de entender" },
        { palabra: "MAGISTRAL", pista: "Maestro o experto" },
        { palabra: "CAPACITACION", pista: "Entrenamiento" },
        { palabra: "RESILIENCIA", pista: "Capacidad de adaptación" },
        { palabra: "SUPERACION", pista: "Vencer obstáculos" },
        { palabra: "PRODUCTIVIDAD", pista: "Eficiencia en el trabajo" },
        { palabra: "CONTRADICCION", pista: "Oposición entre ideas" },
        { palabra: "INNOVADOR", pista: "Que innova o crea novedades" },
        { palabra: "PERSEVERANTE", pista: "Que persevera" },
        { palabra: "ILUMINACION", pista: "Luz brillante" },
        { palabra: "RACIONALIDAD", pista: "Pensamiento lógico" },
        { palabra: "CRECIMIENTO", pista: "Aumento en tamaño o cantidad" },
        { palabra: "ESTRATEGIA", pista: "Planificación" },
        { palabra: "CONVICCION", pista: "Creencia firme" },
        { palabra: "DETERMINANTE", pista: "Que decide o influye" },
        { palabra: "PREDICCION", pista: "Adivinación del futuro" },
        { palabra: "SINCERIDAD", pista: "Honestidad y verdad" },
        { palabra: "DISTINGUIDO", pista: "Elegante y respetado" },
        { palabra: "PLURALIDAD", pista: "Variedad o diversidad" },
        { palabra: "FRATERNIDAD", pista: "Unión y hermandad" },
        { palabra: "INTENSIDAD", pista: "Grado de fuerza" },
        { palabra: "HERMOSAMENTE", pista: "De manera hermosa" },
        { palabra: "INTELIGENCIA", pista: "Facultad mental" },
        { palabra: "POSITIVIDAD", pista: "Pensamiento positivo" },
        { palabra: "SABIDURÍA", pista: "Conocimiento profundo" },
        { palabra: "EFERVESCENCIA", pista: "Agitación o excitación" },
        { palabra: "FUNDAMENTAL", pista: "Básico o esencial" },
        { palabra: "COMPETENCIA", pista: "Rivalidad" },
        { palabra: "AMISTAD", pista: "Relación de amigos" },
        { palabra: "MARAVILLOSO", pista: "Asombroso o impresionante" },
        { palabra: "INDOMABLE", pista: "Que no se puede domar" },
        { palabra: "MAGISTRADO", pista: "Persona en posición judicial" },
        { palabra: "EJEMPLAR", pista: "Que sirve de ejemplo" },
        { palabra: "PERSISTENCIA", pista: "Resistencia a la adversidad" },
        { palabra: "INNOVACIÓN", pista: "Creatividad" },
        { palabra: "COOPERACIÓN", pista: "Trabajo en equipo" },
        { palabra: "HONORABLE", pista: "Digno de honor" },
        { palabra: "RESPONSABLE", pista: "Cumplidor de sus deberes" },
        { palabra: "TRASCENDENTE", pista: "De gran importancia" },
        { palabra: "INVOLUCRAMIENTO", pista: "Participación activa" },
        { palabra: "CONTRADICCIÓN", pista: "Incoherencia" },
        { palabra: "ILUMINADO", pista: "Que ha alcanzado la iluminación" },
        { palabra: "MILAGROSO", pista: "Que parece un milagro" },
        { palabra: "LEGADO", pista: "Herencia o enseñanza" },
        { palabra: "RELEVANCIA", pista: "Importancia" },
        { palabra: "DESTACADO", pista: "Sobresaliente" },
        { palabra: "EXPERIMENTAL", pista: "Relativo a experimentos" },
        { palabra: "MARAVILLA", pista: "Cosa admirable" },
        { palabra: "INDISPENSABLE", pista: "Necesario e imprescindible" },
        { palabra: "ARQUITECTURA", pista: "Diseño de edificios" },
        { palabra: "INTEGRIDAD", pista: "Honestidad y rectitud" },
        { palabra: "CONQUISTADOR", pista: "Persona que conquista" },
        { palabra: "POTENCIALIDAD", pista: "Capacidad de desarrollo" },
        { palabra: "VERSATILIDAD", pista: "Adaptabilidad" },
        { palabra: "SENSIBILIDAD", pista: "Capacidad de sentir" },
        { palabra: "CIVILIZACION", pista: "Sociedad avanzada" },
        { palabra: "CONSCIENCIA", pista: "Conciencia o conocimiento" },
        { palabra: "ARQUEOLOGÍA", pista: "Estudio de restos antiguos" },
        { palabra: "PRINCIPAL", pista: "Más importante" },
        { palabra: "TRANQUILIDAD", pista: "Paz y calma" },
        { palabra: "COMPETITIVIDAD", pista: "Capacidad de competir" },
        { palabra: "COLABORADOR", pista: "Que colabora" },
        { palabra: "RECONOCIMIENTO", pista: "Admire o agradecimiento" },
        { palabra: "INDEPENDIENTE", pista: "Autónomo o libre" },
        { palabra: "COMPRENDER", pista: "Entender algo" },
        { palabra: "RESPECTABLE", pista: "Digno de respeto" },
        { palabra: "MISTERIOSO", pista: "Enigmático" },
        { palabra: "PROFUNDAMENTE", pista: "En gran profundidad" },
        { palabra: "INTOLERANTE", pista: "Falta de tolerancia" },
        { palabra: "ESPECIALIZADO", pista: "Experto en algo" },
        { palabra: "DISCRIMINACION", pista: "Trato injusto" },
        { palabra: "ORGANIZACION", pista: "Grupo ordenado" },
        { palabra: "FRAGMENTADO", pista: "Dividido en fragmentos" },
        { palabra: "SUBLIME", pista: "Espléndido o grandioso" },
        { palabra: "CONTINENTE", pista: "Gran masa de tierra" },
        { palabra: "DETERIORAR", pista: "Hacer que algo empeore" },
        { palabra: "HETEROGENEO", pista: "Diverso o variado" },
        { palabra: "PRESTIGIOSO", pista: "Reconocido y respetado" },
        { palabra: "COMPRENSION", pista: "Entendimiento" },
        { palabra: "INTENCIONAL", pista: "Hecho a propósito" },
        { palabra: "BIBLIOTECA", pista: "Lugar de libros" },
        { palabra: "DOMINANTE", pista: "Que domina o controla" },
        { palabra: "INOCENTE", pista: "Que no es culpable" },
        { palabra: "ILUMINACION", pista: "Luz brillante" },
        { palabra: "REDONDEZ", pista: "Calidad de ser redondo" },
        { palabra: "PRODUCTIVO", pista: "Que produce resultados" },
        { palabra: "INSTITUCION", pista: "Organización formal" },
        { palabra: "CONTAMINACION", pista: "Polución o impureza" },
        { palabra: "FUNDAMENTO", pista: "Base o principio" },
        { palabra: "CONTRADICCION", pista: "Oposición entre ideas" },
        { palabra: "PRESTIGIOSO", pista: "Reconocido y respetado" },
        { palabra: "COMPRENSION", pista: "Entender algo" },
        { palabra: "INSPIRACION", pista: "Estímulo creativo" },
        { palabra: "ATMOSFERA", pista: "Capa de gases alrededor de la Tierra" },
        { palabra: "MISTERIOSO", pista: "Enigmático" },
        { palabra: "ORQUESTA", pista: "Grupo musical" },
        { palabra: "DISCRIMINACION", pista: "Trato injusto" },
        { palabra: "SUPERVIVENCIA", pista: "Permanecer con vida" },
        { palabra: "INNOVACION", pista: "Introducción de novedades" },
        { palabra: "LIBERTAD", pista: "Derecho de elegir" },
        { palabra: "DETERMINACION", pista: "Decisión firme" },
        { palabra: "ALQUIMISTA", pista: "Busca transformar metales" },
        { palabra: "ESPECIALIDAD", pista: "Área de conocimiento" },
        { palabra: "INVESTIGACION", pista: "Búsqueda de información" },
        { palabra: "CONSCIENTEMENTE", pista: "De manera deliberada" },
        { palabra: "DOMINANCIA", pista: "Control o supremacía" },
        { palabra: "DETERMINADO", pista: "Específico o definido" },
        { palabra: "RECOPILACION", pista: "Reunión de datos" },
        { palabra: "BIOLOGIA", pista: "Ciencia de la vida" },
        { palabra: "UNIVERSIDAD", pista: "Institución educativa" },
        { palabra: "ACADEMIA", pista: "Institución educativa" },
        { palabra: "CIVILIZACION", pista: "Sociedad avanzada" },
        { palabra: "COMPLICADO", pista: "Difícil de entender" },
        { palabra: "INVESTIGADOR", pista: "Persona que investiga" },
        { palabra: "ENIGMATICO", pista: "Misterioso o enigmático" },
        { palabra: "EXPERIMENTAL", pista: "Relativo a experimentos" },
        { palabra: "DETERIORO", pista: "Desgaste o deterioro" },
        { palabra: "ENRIQUECEDOR", pista: "Que enriquece" },
        { palabra: "INTRODUCCION", pista: "Inicio o presentación" },
        { palabra: "ORGANIZACIÓN", pista: "Grupo ordenado" },
        { palabra: "DEMOCRACIA", pista: "Sistema de gobierno" },
        { palabra: "JURAMENTO", pista: "Promesa solemne" },
        { palabra: "MISTERIOSO", pista: "Enigmático" },
        { palabra: "PRODIGIOSO", pista: "Asombroso o extraordinario" },
        { palabra: "INTELIGENCIA", pista: "Facultad mental" },
        { palabra: "HERMOSURA", pista: "Belleza" },
        { palabra: "ENAMORAMIENTO", pista: "Sentimiento amoroso inicial" },
        { palabra: "PREDECIR", pista: "Adivinar el futuro" },
        { palabra: "INFINITO", pista: "Ilimitado o eterno" },
        { palabra: "MAGNIFICENCIA", pista: "Esplendor o grandeza" },
        { palabra: "INTERACCION", pista: "Acción de interactuar" },
        { palabra: "POTENCIAL", pista: "Capacidad para desarrollarse" },
        { palabra: "PROFUNDIDAD", pista: "Grandeza o profundidad" },
        { palabra: "FENOMENAL", pista: "Extraordinario o asombroso" },
        { palabra: "ESTABLECIMIENTO", pista: "Lugar de negocio" },
        { palabra: "LITERATURA", pista: "Obra escrita" },
        { palabra: "INMENSIDAD", pista: "Grandeza infinita" },
        { palabra: "PERSISTENTE", pista: "Que no se rinde" },
        { palabra: "DIFERENCIACION", pista: "Distinguir de otros" },
        { palabra: "SOLIDARIDAD", pista: "Unión y apoyo" },
        { palabra: "CONTRASTAR", pista: "Comparar diferencias" },
        { palabra: "INTERCULTURAL", pista: "Entre diferentes culturas" },
        { palabra: "GENEROSIDAD", pista: "Dar sin esperar" },
        { palabra: "HORIZONTE", pista: "Línea que separa cielo y tierra" },
        { palabra: "INCORPORACION", pista: "Inclusión" },
        { palabra: "IDENTIFICACION", pista: "Reconocer algo o alguien" },
        { palabra: "BIOGRAFIA", pista: "Historia de una persona" },
        { palabra: "INTELIGENTE", pista: "Persona con capacidad mental" },
        { palabra: "CULTIVADO", pista: "Educado y refinado" },
        { palabra: "IMAGINACION", pista: "Facultad de crear imágenes" },
        { palabra: "CONFIDENCIAL", pista: "Secreto o privado" },
        { palabra: "IMPRESCINDIBLE", pista: "Necesario e indispensable" },
        { palabra: "IMPLACABLE", pista: "Que no perdona" },
        { palabra: "REPERCUSION", pista: "Impacto o consecuencia" },
        { palabra: "HERMOSURA", pista: "Belleza" },
        { palabra: "AVENTURERO", pista: "Persona que busca aventuras" },
        { palabra: "INTROVERTIDO", pista: "Persona reservada" },
        { palabra: "CONTEMPLACION", pista: "Observación con atención" },
        { palabra: "EXTRAORDINARIO", pista: "Fuera de lo común" },
        { palabra: "IMAGINATIVO", pista: "Creativo y fantasioso" },
        { palabra: "DETERMINADO", pista: "Decidido y enfocado" },
        { palabra: "COMPASION", pista: "Sentimiento de empatía" },
        { palabra: "COMPRENSIBLE", pista: "Fácil de entender" },
        { palabra: "MAGISTRAL", pista: "Maestro o experto" },
        { palabra: "CAPACITACION", pista: "Entrenamiento" },
        { palabra: "RESILIENCIA", pista: "Capacidad de adaptación" },
        { palabra: "SUPERACION", pista: "Vencer obstáculos" },
        { palabra: "PRODUCTIVIDAD", pista: "Eficiencia en el trabajo" },
        { palabra: "CONTRADICCION", pista: "Oposición entre ideas" },
        { palabra: "INNOVADOR", pista: "Que innova o crea novedades" },
        { palabra: "PERSEVERANTE", pista: "Que persevera" },
        { palabra: "ILUMINACION", pista: "Luz brillante" },
        { palabra: "RACIONALIDAD", pista: "Pensamiento lógico" },
        { palabra: "CRECIMIENTO", pista: "Aumento en tamaño o cantidad" },
        { palabra: "ESTRATEGIA", pista: "Planificación" },
        { palabra: "CONVICCION", pista: "Creencia firme" },
        { palabra: "DETERMINANTE", pista: "Que decide o influye" },
        { palabra: "PREDICCION", pista: "Adivinación del futuro" },
        { palabra: "SINCERIDAD", pista: "Honestidad y verdad" },
        { palabra: "DISTINGUIDO", pista: "Elegante y respetado" },
        { palabra: "PLURALIDAD", pista: "Variedad o diversidad" },
        { palabra: "FRATERNIDAD", pista: "Unión y hermandad" },
        { palabra: "INTENSIDAD", pista: "Grado de fuerza" },
        { palabra: "HERMOSAMENTE", pista: "De manera hermosa" },
        { palabra: "INTELIGENCIA", pista: "Facultad mental" },
        { palabra: "POSITIVIDAD", pista: "Pensamiento positivo" },
        { palabra: "SABIDURIA", pista: "Conocimiento profundo" },
        { palabra: "EFERVESCENCIA", pista: "Agitación o excitación" },
        { palabra: "FUNDAMENTAL", pista: "Básico o esencial" },
        { palabra: "COMPETENCIA", pista: "Rivalidad" },
        { palabra: "AMISTAD", pista: "Relación de amigos" },
        { palabra: "MARAVILLOSO", pista: "Asombroso o impresionante" },
        { palabra: "INDOMABLE", pista: "Que no se puede domar" },
        { palabra: "MAGISTRADO", pista: "Persona en posición judicial" },
        { palabra: "EJEMPLAR", pista: "Que sirve de ejemplo" },
        { palabra: "PERSISTENCIA", pista: "Resistencia a la adversidad" },
        { palabra: "INNOVACION", pista: "Creatividad" },
        { palabra: "COOPERACION", pista: "Trabajo en equipo" },
        { palabra: "HONORABLE", pista: "Digno de honor" },
        { palabra: "RESPONSABLE", pista: "Cumplidor de sus deberes" },
        { palabra: "TRASCENDENTE", pista: "De gran importancia" },
        { palabra: "INVOLUCRAMIENTO", pista: "Participación activa" },
        { palabra: "CONTRADICCION", pista: "Incoherencia" },
        { palabra: "ILUMINADO", pista: "Que ha alcanzado la iluminación" },
        { palabra: "MILAGROSO", pista: "Que parece un milagro" },
        { palabra: "LEGADO", pista: "Herencia o enseñanza" },
        { palabra: "RELEVANCIA", pista: "Importancia" },
        { palabra: "DESTACADO", pista: "Sobresaliente" },
        { palabra: "EXPERIMENTAL", pista: "Relativo a experimentos" },
        { palabra: "MARAVILLA", pista: "Cosa admirable" },
        { palabra: "INDISPENSABLE", pista: "Necesario e imprescindible" },
        { palabra: "ARQUITECTURA", pista: "Diseño de edificios" },
        { palabra: "INTEGRIDAD", pista: "Honestidad y rectitud" },
        { palabra: "CONQUISTADOR", pista: "Persona que conquista" },
        { palabra: "POTENCIALIDAD", pista: "Capacidad de desarrollo" },
        { palabra: "VERSATILIDAD", pista: "Adaptabilidad" },
        { palabra: "SENSIBILIDAD", pista: "Capacidad de sentir" },
        { palabra: "CIVILIZACION", pista: "Sociedad avanzada" },
        { palabra: "CONSCIENCIA", pista: "Conciencia o conocimiento" },
        { palabra: "ARQUEOLOGIA", pista: "Estudio de restos antiguos" },
        { palabra: "PRINCIPAL", pista: "Más importante" },
        { palabra: "TRANQUILIDAD", pista: "Paz y calma" },
        { palabra: "COMPETITIVIDAD", pista: "Capacidad de competir" },
        { palabra: "COLABORADOR", pista: "Que colabora" },
        { palabra: "RECONOCIMIENTO", pista: "Admire o agradecimiento" },
        { palabra: "INDEPENDIENTE", pista: "Autónomo o libre" },
        { palabra: "COMPRENDER", pista: "Entender algo" },
        { palabra: "RESPECTABLE", pista: "Digno de respeto" },
        { palabra: "MISTERIOSO", pista: "Enigmático" },
        { palabra: "PROFUNDAMENTE", pista: "En gran profundidad" },
        { palabra: "INTOLERANTE", pista: "Falta de tolerancia" },
        { palabra: "ESPECIALIZADO", pista: "Experto en algo" },
        { palabra: "DISCRIMINACION", pista: "Trato injusto" },
        { palabra: "ORGANIZACION", pista: "Grupo ordenado" },
        { palabra: "FRAGMENTADO", pista: "Dividido en fragmentos" },
        { palabra: "SUBLIME", pista: "Espléndido o grandioso" },
        { palabra: "CONTINENTE", pista: "Gran masa de tierra" },
        { palabra: "DETERIORAR", pista: "Hacer que algo empeore" },
        { palabra: "HETEROGENEO", pista: "Diverso o variado" },
        { palabra: "PRESTIGIOSO", pista: "Reconocido y respetado" },
        { palabra: "COMPRENSION", pista: "Entendimiento" },
        { palabra: "INTENCIONAL", pista: "Hecho a propósito" },
        { palabra: "BIBLIOTECA", pista: "Lugar de libros" },
        { palabra: "DOMINANTE", pista: "Que domina o controla" },
        { palabra: "INOCENTE", pista: "Que no es culpable" },
        { palabra: "ILUMINACION", pista: "Luz brillante" },
        { palabra: "REDONDEZ", pista: "Calidad de ser redondo" },
        { palabra: "PRODUCTIVO", pista: "Que produce resultados" },
        { palabra: "INSTITUCION", pista: "Organización formal" },
        { palabra: "CONTAMINACION", pista: "Polución o impureza" },
        { palabra: "FUNDAMENTO", pista: "Base o principio" },
        { palabra: "CONTRADICCION", pista: "Oposición entre ideas" },
        { palabra: "PRESTIGIOSO", pista: "Reconocido y respetado" },
        { palabra: "COMPRENSION", pista: "Entender algo" },
        { palabra: "INSPIRACION", pista: "Estímulo creativo" },
        { palabra: "ATMOSFERA", pista: "Capa de gases alrededor de la Tierra" },
        { palabra: "MISTERIOSO", pista: "Enigmático" },
        { palabra: "ORQUESTA", pista: "Grupo musical" },
        { palabra: "DISCRIMINACION", pista: "Trato injusto" },
        { palabra: "SUPERVIVENCIA", pista: "Permanecer con vida" },
        { palabra: "INNOVACION", pista: "Introducción de novedades" },
        { palabra: "LIBERTAD", pista: "Derecho de elegir" },
        { palabra: "DETERMINACION", pista: "Decisión firme" },
        { palabra: "ALQUIMISTA", pista: "Busca transformar metales" },
        { palabra: "ESPECIALIDAD", pista: "Área de conocimiento" },
        { palabra: "INVESTIGACION", pista: "Búsqueda de información" },
        { palabra: "CONSCIENTEMENTE", pista: "De manera deliberada" },
        { palabra: "DOMINANCIA", pista: "Control o supremacía" },
        { palabra: "DETERMINADO", pista: "Específico o definido" },
        { palabra: "RECOPILACION", pista: "Reunión de datos" },
        { palabra: "BIOLOGIA", pista: "Ciencia de la vida" },
        { palabra: "UNIVERSIDAD", pista: "Institución educativa" },
        { palabra: "ACADEMIA", pista: "Institución educativa" },
        { palabra: "CIVILIZACION", pista: "Sociedad avanzada" },
        { palabra: "COMPLICADO", pista: "Difícil de entender" },
        { palabra: "INVESTIGADOR", pista: "Persona que investiga" },
        { palabra: "ENIGMATICO", pista: "Misterioso o enigmático" },
        { palabra: "EXPERIMENTAL", pista: "Relativo a experimentos" },
        { palabra: "DETERIORO", pista: "Desgaste o deterioro" },
        { palabra: "ENRIQUECEDOR", pista: "Que enriquece" },
        { palabra: "INTRODUCCION", pista: "Inicio o presentación" },
        { palabra: "ORGANIZACION", pista: "Grupo ordenado" },
        { palabra: "DEMOCRACIA", pista: "Sistema de gobierno" },
        { palabra: "JURAMENTO", pista: "Promesa solemne" },
        { palabra: "MISTERIOSO", pista: "Enigmático" },
        { palabra: "PRODIGIOSO", pista: "Asombroso o extraordinario" },
        { palabra: "INTELIGENCIA", pista: "Facultad mental" },
        { palabra: "HERMOSURA", pista: "Belleza" },
        { palabra: "ENAMORAMIENTO", pista: "Sentimiento amoroso inicial" },
        { palabra: "PREDECIR", pista: "Adivinar el futuro" },
        { palabra: "INFINITO", pista: "Ilimitado o eterno" },
        { palabra: "MAGNIFICENCIA", pista: "Esplendor o grandeza" },
        { palabra: "INTERACCION", pista: "Acción de interactuar" },
        { palabra: "POTENCIAL", pista: "Capacidad para desarrollarse" },
        { palabra: "PROFUNDIDAD", pista: "Grandeza o profundidad" },
        { palabra: "FENOMENAL", pista: "Extraordinario o asombroso" },
        { palabra: "ESTABLECIMIENTO", pista: "Lugar de negocio" },
        { palabra: "LITERATURA", pista: "Obra escrita" },
        { palabra: "INMENSIDAD", pista: "Grandeza infinita" },
        { palabra: "PERSISTENTE", pista: "Que no se rinde" },
        { palabra: "DIFERENCIACION", pista: "Distinguir de otros" },
        { palabra: "SOLIDARIDAD", pista: "Unión y apoyo" },
        { palabra: "CONTRASTAR", pista: "Comparar diferencias" },
        { palabra: "INTERCULTURAL", pista: "Entre diferentes culturas" },
        { palabra: "GENEROSIDAD", pista: "Dar sin esperar" },
        { palabra: "HORIZONTE", pista: "Línea que separa cielo y tierra" },
        { palabra: "INCORPORACION", pista: "Inclusión" },
        { palabra: "IDENTIFICACION", pista: "Reconocer algo o alguien" },
        { palabra: "BIOGRAFIA", pista: "Historia de una persona" },
        { palabra: "INTELIGENTE", pista: "Persona con capacidad mental" },
        { palabra: "CULTIVADO", pista: "Educado y refinado" },
        { palabra: "IMAGINACION", pista: "Facultad de crear imágenes" },
        { palabra: "CONFIDENCIAL", pista: "Secreto o privado" },
        { palabra: "IMPRESCINDIBLE", pista: "Necesario e indispensable" },
        { palabra: "IMPLACABLE", pista: "Que no perdona" },
        { palabra: "REPERCUSION", pista: "Impacto o consecuencia" },
        { palabra: "HERMOSURA", pista: "Belleza" },
        { palabra: "AVENTURERO", pista: "Persona que busca aventuras" },
        { palabra: "INTROVERTIDO", pista: "Persona reservada" },
        { palabra: "CONTEMPLACION", pista: "Observación con atención" },
        { palabra: "EXTRAORDINARIO", pista: "Fuera de lo común" },
        { palabra: "IMAGINATIVO", pista: "Creativo y fantasioso" },
        { palabra: "DETERMINADO", pista: "Decidido y enfocado" },
        { palabra: "COMPASION", pista: "Sentimiento de empatía" },
        { palabra: "COMPRENSIBLE", pista: "Fácil de entender" },
        { palabra: "MAGISTRAL", pista: "Maestro o experto" },
        { palabra: "CAPACITACION", pista: "Entrenamiento" },
        { palabra: "RESILIENCIA", pista: "Capacidad de adaptación" },
        { palabra: "SUPERACION", pista: "Vencer obstáculos" },
        { palabra: "PRODUCTIVIDAD", pista: "Eficiencia en el trabajo" },
        { palabra: "CONTRADICCION", pista: "Oposición entre ideas" },
        { palabra: "INNOVADOR", pista: "Que innova o crea novedades" },
        { palabra: "PERSEVERANTE", pista: "Que persevera" },
        { palabra: "ILUMINACION", pista: "Luz brillante" },
        { palabra: "RACIONALIDAD", pista: "Pensamiento lógico" },
        { palabra: "CRECIMIENTO", pista: "Aumento en tamaño o cantidad" },
        { palabra: "ESTRATEGIA", pista: "Planificación" },
        { palabra: "CONVICCION", pista: "Creencia firme" },
        { palabra: "DETERMINANTE", pista: "Que decide o influye" },
        { palabra: "PREDICCION", pista: "Adivinación del futuro" },
        { palabra: "SINCERIDAD", pista: "Honestidad y verdad" },
        { palabra: "DISTINGUIDO", pista: "Elegante y respetado" },
        { palabra: "PLURALIDAD", pista: "Variedad o diversidad" },
        { palabra: "FRATERNIDAD", pista: "Unión y hermandad" },
        { palabra: "INTENSIDAD", pista: "Grado de fuerza" },
        { palabra: "HERMOSAMENTE", pista: "De manera hermosa" },
        { palabra: "INTELIGENCIA", pista: "Facultad mental" },
        { palabra: "POSITIVIDAD", pista: "Pensamiento positivo" },
        { palabra: "SABIDURIA", pista: "Conocimiento profundo" },
        { palabra: "EFERVESCENCIA", pista: "Agitación o excitación" },
        { palabra: "FUNDAMENTAL", pista: "Básico o esencial" },
        { palabra: "COMPETENCIA", pista: "Rivalidad" },
        { palabra: "AMISTAD", pista: "Relación de amigos" },
        { palabra: "MARAVILLOSO", pista: "Asombroso o impresionante" },
        { palabra: "INDOMABLE", pista: "Que no se puede domar" },
        { palabra: "MAGISTRADO", pista: "Persona en posición judicial" },
        { palabra: "EJEMPLAR", pista: "Que sirve de ejemplo" },
        { palabra: "PERSISTENCIA", pista: "Resistencia a la adversidad" },
        { palabra: "INNOVACION", pista: "Creatividad" },
        { palabra: "COOPERACION", pista: "Trabajo en equipo" },
        { palabra: "HONORABLE", pista: "Digno de honor" },
        { palabra: "RESPONSABLE", pista: "Cumplidor de sus deberes" },
        { palabra: "TRASCENDENTE", pista: "De gran importancia" },
        { palabra: "INVOLUCRAMIENTO", pista: "Participación activa" },
        { palabra: "CONTRADICCION", pista: "Incoherencia" },
        { palabra: "ILUMINADO", pista: "Que ha alcanzado la iluminación" },
        { palabra: "MILAGROSO", pista: "Que parece un milagro" },
        { palabra: "LEGADO", pista: "Herencia o enseñanza" },
        { palabra: "RELEVANCIA", pista: "Importancia" },
        { palabra: "DESTACADO", pista: "Sobresaliente" },
        { palabra: "EXPERIMENTAL", pista: "Relativo a experimentos" },
        { palabra: "MARAVILLA", pista: "Cosa admirable" },
        { palabra: "INDISPENSABLE", pista: "Necesario e imprescindible" },
        { palabra: "ARQUITECTURA", pista: "Diseño de edificios" },
        { palabra: "INTEGRIDAD", pista: "Honestidad y rectitud" },
        { palabra: "CONQUISTADOR", pista: "Persona que conquista" },
        { palabra: "POTENCIALIDAD", pista: "Capacidad de desarrollo" },
        { palabra: "VERSATILIDAD", pista: "Adaptabilidad" },
        { palabra: "SENSIBILIDAD", pista: "Capacidad de sentir" },
        { palabra: "CIVILIZACION", pista: "Sociedad avanzada" },  
];

function seleccionarPalabraAleatoria() {
const indiceAleatorio = Math.floor(Math.random() * palabras.length);
return palabras[indiceAleatorio];
}


function seleccionarPalabraAleatoria() {
const indiceAleatorio = Math.floor(Math.random() * palabras.length);
return palabras[indiceAleatorio];
}

let palabraSeleccionada = seleccionarPalabraAleatoria();
let wordToGuess = palabraSeleccionada.palabra;
let pista = palabraSeleccionada.pista;



// Inicializa variables
let guesses = 0;
let mistakes = 0;
let guessedWord = "";

// Obtén elementos del DOM
const typeInput = document.querySelector(".type-input");
const wordDisplay = document.querySelector(".word");
const guessDisplay = document.querySelector(".guess span");
const mistakesDisplay = document.querySelector(".wrong span");
const hintDisplay = document.querySelector(".hint span");
const resetButton = document.querySelector(".reset");
const showHintButton = document.querySelector(".showhint");

// Evento para mostrar una pista relacionada a la palabra
showHintButton.addEventListener("click", () => {
hintDisplay.textContent = "Pista: " + pista;
});

// Inicializa la palabra oculta
for (let i = 0; i < wordToGuess.length; i++) {
guessedWord += "_";
}

// Muestra la palabra oculta en la pantalla
wordDisplay.textContent = guessedWord;

// Evento para adivinar letras
typeInput.addEventListener("input", () => {
const letter = typeInput.value.toUpperCase();
typeInput.value = "";

if (wordToGuess.includes(letter)) {
    // La letra está en la palabra
    for (let i = 0; i < wordToGuess.length; i++) {
        if (wordToGuess[i] === letter) {
            guessedWord = guessedWord.substr(0, i) + letter + guessedWord.substr(i + 1);
        }
    }
} else {
    // La letra no está en la palabra
    mistakes++;
}

guesses++;
wordDisplay.textContent = guessedWord;
guessDisplay.textContent = guesses;
mistakesDisplay.textContent = mistakes;

// Verifica si se ha adivinado la palabra completa
if (guessedWord === wordToGuess) {
    alert("¡Has ganado! La palabra es: " + wordToGuess);
} else if (mistakes >= 6) {
    alert("¡Has perdido! La palabra era: " + wordToGuess);
}
});

resetButton.addEventListener("click", () => {
// Selecciona una nueva palabra aleatoria y su pista
palabraSeleccionada = seleccionarPalabraAleatoria();
wordToGuess = palabraSeleccionada.palabra;
pista = palabraSeleccionada.pista;

guesses = 0;
mistakes = 0;
guessedWord = "";
for (let i = 0; i < wordToGuess.length; i++) {
    guessedWord += "_";
}
wordDisplay.textContent = guessedWord;
guessDisplay.textContent = guesses;
mistakesDisplay.textContent = mistakes;
hintDisplay.textContent = ""; // Limpia la pista mostrada
});