// Define the word to guess
//const wordToGuess = "HELLO";

const words = [
    { word: "EXCELLENT", clue: "Synonym of outstanding" },
    { word: "IMMORTAL", clue: "That cannot die" },
    { word: "RELEVANT", clue: "Important or significant" },
    { word: "ARCHITECT", clue: "Designer of buildings" },
    { word: "MAGNIFICENT", clue: "Splendid or grand" },
    { word: "PROFESSION", clue: "Occupation or trade" },
    { word: "PLUTOCRACY", clue: "Government by the rich" },
    { word: "ESOTERIC", clue: "Secret or mysterious knowledge" },
    { word: "DISDAIN", clue: "Feeling of contempt" },
    { word: "ELOQUENT", clue: "Expressing oneself fluently" },
    { word: "SOPHISTICATED", clue: "Elegant and complex" },
    { word: "EXPERIMENT", clue: "Scientific test or trial" },
    { word: "DELIBERATE", clue: "Consider carefully" },
    { word: "PERSEVERE", clue: "Persist in an action" },
    { word: "RECOGNIZED", clue: "Admired or identified" },
    { word: "ABSTRACTION", clue: "Non-concrete concept or idea" },
    { word: "AUTHORITY", clue: "Power or dominance" },
    { word: "JURISPRUDENCE", clue: "Study of law" },
    { word: "CONSTITUTION", clue: "Fundamental law of a country" },
    { word: "FUNDAMENTAL", clue: "Essential or basic" },
    { word: "INTELLIGENT", clue: "Person with mental capacity" },
    { word: "CURIOSITY", clue: "Desire to know" },
    { word: "HYPOTHETICAL", clue: "Based on assumptions" },
    { word: "CONTRADICTION", clue: "Opposition between ideas" },
    { word: "ILLUMINATION", clue: "Bright light" },
    { word: "INFATUATION", clue: "Initial romantic feeling" },
    { word: "FRAGMENT", clue: "Separated part of a whole" },
    { word: "CONTEMPLATE", clue: "Observe with attention" },
    { word: "INTANGIBLE", clue: "Cannot be touched" },
    { word: "ABUNDANT", clue: "In large quantity" },
    { word: "PROMINENT", clue: "Outstanding or noteworthy" },
    { word: "TOLERANCE", clue: "Respect for differences" },
    { word: "CIRCUMFERENCE", clue: "Line that surrounds a circle" },
    { word: "DELINQUENT", clue: "Criminal or lawbreaker" },
    { word: "CONVERGENCE", clue: "Coming together of ideas" },
    { word: "INSIGHTFUL", clue: "Sharp in observation" },
    { word: "PARADOX", clue: "Apparent contradiction" },
    { word: "TRANSCENDENT", clue: "Important and profound" },
    { word: "ABUNDANCE", clue: "Large quantity of something" },
    { word: "AMBIGUOUS", clue: "Having multiple meanings" },
    { word: "DECADENCE", clue: "Decline or deterioration" },
    { word: "PRODIGIOUS", clue: "Extraordinary or astonishing" },
    { word: "CONSCIOUS", clue: "Having awareness" },
    { word: "VULNERABLE", clue: "Susceptible to harm" },
    { word: "HETEROGENEOUS", clue: "Diverse or varied" },
    { word: "TRANSCENDENTAL", clue: "Of great importance" },
    { word: "COMPELLING", clue: "Strongly convincing" },
    { word: "PRESTIGE", clue: "Recognition and respect" },
    { word: "SPECTACLE", clue: "Show or presentation" },
    { word: "ASTRONOMY", clue: "Science of celestial objects" },
    { word: "DISCOVERY", clue: "Important finding" },
    { word: "CONSEQUENTIAL", clue: "Having logical implications" },
    { word: "PERSISTENT", clue: "Not giving up" },
    { word: "DIVERSITY", clue: "Variety of things" },
    { word: "INTENTIONAL", clue: "Done on purpose" },
    { word: "PROPORTION", clue: "Relation between parts" },
    { word: "INVOLVED", clue: "Engaged in something" },
    { word: "UNKNOWN", clue: "Not known who or what it is" },
    { word: "INCORPORATE", clue: "Include or add" },
    { word: "BALANCE", clue: "Harmony and stability" },
    { word: "DISCRETION", clue: "Caution and reserve" },
    { word: "DISCREPANCY", clue: "Disagreement or difference" },
    { word: "CONFRONT", clue: "Face something" },
    { word: "AUTHORITARIAN", clue: "Exercising authority" },
    { word: "INDISPENSABLE", clue: "Necessary and essential" },
    { word: "ELAPSE", clue: "Pass by" },
    { word: "COOPERATION", clue: "Joint effort" },
    { word: "SUPERFICIAL", clue: "Lacking depth" },
    { word: "POTENTIAL", clue: "Capability for development" },
    { word: "RELEVANCE", clue: "Importance or relevance" },
    { word: "DICTATORSHIP", clue: "Authoritarian rule" },
    { word: "OATH", clue: "Solemn promise" },
    { word: "MYSTERIOUS", clue: "Puzzling or enigmatic" },
    { word: "SPIRITUAL", clue: "Related to the spirit" },
    { word: "RESERVED", clue: "Keeping secrets" },
    { word: "CONTINENT", clue: "Large landmass" },
    { word: "INDEPENDENT", clue: "Free and autonomous" },
    { word: "DOMINANT", clue: "Exerting control" },
    { word: "INNOCENT", clue: "Not guilty" },
    { word: "ILLUMINATION", clue: "Bright light" },
    { word: "ROUNDNESS", clue: "Quality of being round" },
    { word: "PRODUCTIVE", clue: "Yielding results" },
    { word: "INSTITUTION", clue: "Formal organization" },
    { word: "CONTAMINATION", clue: "Pollution or impurity" },
    { word: "FOUNDATION", clue: "Basis or principle" },
    { word: "CONTRADICTION", clue: "Opposition between ideas" },
    { word: "PRESTIGIOUS", clue: "Recognized and respected" },
    { word: "UNDERSTANDING", clue: "Comprehending something" },
    { word: "INSPIRATION", clue: "Creative stimulation" },
    { word: "ATMOSPHERE", clue: "Layer of gases around Earth" },
    { word: "MYSTERIOUS", clue: "Enigmatic" },
    { word: "ORCHESTRA", clue: "Musical group" },
    { word: "DISCRIMINATION", clue: "Unfair treatment" },
    { word: "SURVIVAL", clue: "Remaining alive" },
    { word: "INNOVATION", clue: "Introduction of novelties" },
    { word: "FREEDOM", clue: "Right to choose" },
    { word: "DETERMINATION", clue: "Firm decision" },
    { word: "ALCHEMY", clue: "Seeks to transform metals" },
{ word: "SPECIALTY", clue: "Area of expertise" },
{ word: "RESEARCH", clue: "Search for information" },
{ word: "CONSCIOUSLY", clue: "Deliberately" },
{ word: "DOMINANCE", clue: "Control or supremacy" },
{ word: "DETERMINED", clue: "Specific or defined" },
{ word: "COMPILATION", clue: "Gathering of data" },
{ word: "BIOLOGY", clue: "Science of life" },
{ word: "UNIVERSITY", clue: "Educational institution" },
{ word: "ACADEMY", clue: "Educational institution" },
{ word: "CIVILIZATION", clue: "Advanced society" },
{ word: "COMPLICATED", clue: "Difficult to understand" },
{ word: "RESEARCHER", clue: "Person who investigates" },
{ word: "ENIGMATIC", clue: "Mysterious or enigmatic" },
{ word: "EXPERIMENTAL", clue: "Relating to experiments" },
{ word: "DETERIORATION", clue: "Wear or deterioration" },
{ word: "ENRICHING", clue: "That enriches" },
{ word: "INTRODUCTION", clue: "Beginning or presentation" },
{ word: "ORGANIZATION", clue: "Ordered group" },
{ word: "DEMOCRACY", clue: "System of government" },
{ word: "MULTIFACETED", clue: "Having many facets" },
{ word: "CONSTANTINOPLE", clue: "Ancient city" },
{ word: "CONFRONTATION", clue: "Confrontation" },
{ word: "UNDERSTANDING", clue: "Comprehension" },
{ word: "DETERIORATE", clue: "To make something worse" },
{ word: "INFLUENCE", clue: "Power to affect" },
{ word: "SUBLIME", clue: "Very beautiful or grand" },
{ word: "WISDOM", clue: "Deep knowledge" },
{ word: "ABUNDANCE", clue: "Great quantity" },
{ word: "FUNDAMENTAL", clue: "Essential" },
{ word: "CONTINUITY", clue: "Persistence over time" },
{ word: "SPECTATOR", clue: "Person who watches" },
{ word: "INVOLVEMENT", clue: "Active participation" },
{ word: "COEXISTENCE", clue: "Living together" },
{ word: "RECOGNITION", clue: "Admiration or acknowledgment" },
{ word: "SATISFACTION", clue: "Feeling of contentment" },
{ word: "IMPRESSIVE", clue: "Causing an impression" },
{ word: "EFFORT", clue: "Hard work" },
{ word: "INTELLIGENCE", clue: "Mental capacity" },
{ word: "PROSPERITY", clue: "Success and well-being" },
{ word: "BEGINNER", clue: "Person who starts" },
{ word: "CONTRADICTORY", clue: "Opposite or contrary" },
{ word: "ENLIGHTENED", clue: "Having reached enlightenment" },
{ word: "REPRESENTATION", clue: "Act of representing" },
{ word: "ESTABLISHED", clue: "Established or fixed" },
{ word: "FRUSTRATION", clue: "Feeling of failure" },
{ word: "DETERMINATION", clue: "Firm decision" },
{ word: "EXCELLENCE", clue: "Superior quality" },
{ word: "SENSITIVITY", clue: "Ability to feel" },
{ word: "COLLABORATION", clue: "Teamwork" },
{ word: "INDIFFERENCE", clue: "Lack of interest" },
{ word: "DISCONTENT", clue: "Lack of satisfaction" },
{ word: "PERSISTENCE", clue: "Continuity in action" },
{ word: "COMPETITIVE", clue: "That competes" },
{ word: "INTOLERANCE", clue: "Lack of tolerance" },
{ word: "RESEARCH", clue: "Search for knowledge" },
{ word: "RESPONSIBILITY", clue: "Duty or burden" },
{ word: "PERSISTENT", clue: "That does not give up" },
{ word: "CONTINENTAL", clue: "Related to continents" },
{ word: "EXPLORATION", clue: "Action of exploring" },
{ word: "ACADEMY", clue: "Educational institution" },
{ word: "SUSTAINABILITY", clue: "Ability to sustain" },
{ word: "INDEPENDENTLY", clue: "Without depending on others" },
{ word: "BIOLOGY", clue: "Science of life" },
{ word: "LEARNING", clue: "Process of learning" },
{ word: "UNDERSTAND", clue: "To comprehend something" },
{ word: "DIVERSIFICATION", clue: "Variation or expansion" },
{ word: "IMMIGRATION", clue: "Migration to another country" },
{ word: "CONTRADICTION", clue: "Opposition between ideas" },
{ word: "DETERIORATION", clue: "Wear or weakening" },
{ word: "STRATEGIC", clue: "Related to strategies" },
{ word: "HUMANITY", clue: "Human qualities" },
{ word: "PRESTIGE", clue: "Recognition and respect" },
{ word: "VERSATILITY", clue: "Ability to adapt" },
{ word: "INTERESTING", clue: "That arouses interest" },
{ word: "CREATIVITY", clue: "Ability to create" },
{ word: "BEAUTY", clue: "Beauty or attractiveness" },
{ word: "INFATUATION", clue: "Initial romantic feeling" },
{ word: "PREDICT", clue: "To guess the future" },
{ word: "INFINITE", clue: "Unlimited or eternal" },
{ word: "MAGNIFICENCE", clue: "Splendor or greatness" },
{ word: "INTERACTION", clue: "Action of interacting" },
{ word: "POTENTIAL", clue: "Capacity for development" },
{ word: "DEPTH", clue: "Greatness or profundity" },
{ word: "PHENOMENAL", clue: "Extraordinary or astonishing" },
{ word: "ESTABLISHMENT", clue: "Place of business" },
{ word: "LITERATURE", clue: "Written work" },
{ word: "VASTNESS", clue: "Infinite greatness" },
{ word: "PERSISTENT", clue: "That does not give up" },
{ word: "DIFFERENTIATION", clue: "Distinguishing from others" },
{ word: "SOLIDARITY", clue: "Unity and support" },
{ word: "CONTRAST", clue: "Compare differences" },
{ word: "INTERCULTURAL", clue: "Between different cultures" },
{ word: "GENEROSITY", clue: "Giving without expecting" },
{ word: "HORIZON", clue: "Line separating sky and earth" },
{ word: "INCORPORATION", clue: "Inclusion" },
{ word: "IDENTIFICATION", clue: "Recognizing something or someone" },
{ word: "BIOGRAPHY", clue: "History of a person" },
{ word: "INTELLIGENT", clue: "Person with mental capacity" },
{ word: "CULTIVATED", clue: "Educated and refined" },
{ word: "IMAGINATION", clue: "Faculty of creating images" },
{ word: "CONFIDENTIAL", clue: "Secret or private" },
{ word: "INDISPENSABLE", clue: "Necessary and essential" },
{ word: "RUTHLESS", clue: "Unforgiving" },
{ word: "IMPACT", clue: "Effect or consequence" },
{ word: "BEAUTY", clue: "Beauty" },
{ word: "ADVENTURER", clue: "Person who seeks adventures" },
{ word: "INTROVERTED", clue: "Reserved person" },
{ word: "CONTEMPLATION", clue: "Observation with attention" },
{ word: "EXTRAORDINARY", clue: "Out of the ordinary" },
{ word: "IMAGINATIVE", clue: "Creative and imaginative" },
{ word: "DETERMINED", clue: "Decisive and focused" },
{ word: "COMPASSION", clue: "Feeling of empathy" },
{ word: "COMPREHENSIBLE", clue: "Easy to understand" },
{ word: "MASTERFUL", clue: "Master or expert" },
{ word: "TRAINING", clue: "Training" },
{ word: "RESILIENCE", clue: "Adaptation capacity" },
{ word: "OVERCOMING", clue: "Overcoming obstacles" },
{ word: "PRODUCTIVITY", clue: "Efficiency at work" },
{ word: "CONTRADICTION", clue: "Opposition between ideas" },
{ word: "INNOVATIVE", clue: "Innovative or creating novelties" },
{ word: "PERSISTENT", clue: "Persevering" },
{ word: "ILLUMINATION", clue: "Bright light" },
{ word: "RATIONALITY", clue: "Logical thinking" },
{ word: "GROWTH", clue: "Increase in size or quantity" },
{ word: "STRATEGY", clue: "Planning" },
{ word: "CONVICTION", clue: "Firm belief" },
{ word: "DETERMINING", clue: "Decisive or influential" },
{ word: "PREDICTION", clue: "Future prediction" },
{ word: "SINCERITY", clue: "Honesty and truth" },
{ word: "DISTINGUISHED", clue: "Elegant and respected" },
{ word: "PLURALITY", clue: "Variety or diversity" },
{ word: "FRATERNITY", clue: "Unity and brotherhood" },
{ word: "INTENSITY", clue: "Degree of strength" },
{ word: "BEAUTIFULLY", clue: "In a beautiful manner" },
{ word: "INTELLIGENCE", clue: "Mental faculty" },
{ word: "POSITIVITY", clue: "Positive thinking" },
{ word: "WISDOM", clue: "Deep knowledge" },
{ word: "EFFERVESCENCE", clue: "Agitation or excitement" },
{ word: "FUNDAMENTAL", clue: "Basic or essential" },
{ word: "COMPETITION", clue: "Rivalry" },
{ word: "FRIENDSHIP", clue: "Friendship relationship" },
{ word: "MARVELOUS", clue: "Amazing or impressive" },
{ word: "INDOMITABLE", clue: "Unconquerable" },
{ word: "MAGISTRATE", clue: "Person in a judicial position" },
{ word: "EXEMPLARY", clue: "Serving as an example" },
{ word: "PERSISTENCE", clue: "Resilience in adversity" },
{ word: "INNOVATION", clue: "Creativity" },
{ word: "COOPERATION", clue: "Teamwork" },
{ word: "HONORABLE", clue: "Worthy of honor" },
{ word: "RESPONSIBLE", clue: "Fulfilling one's duties" },
{ word: "SIGNIFICANT", clue: "Of great importance" },
{ word: "INVOLVEMENT", clue: "Active participation" },
{ word: "CONTRADICTION", clue: "Incoherence" },
{ word: "ENLIGHTENED", clue: "Having reached enlightenment" },
{ word: "MIRACULOUS", clue: "Seeming like a miracle" },
{ word: "LEGACY", clue: "Inheritance or teaching" },
{ word: "RELEVANCE", clue: "Importance" },
{ word: "OUTSTANDING", clue: "Outstanding" },
{ word: "EXPERIMENTAL", clue: "Related to experiments" },
{ word: "WONDER", clue: "Admirable thing" },
{ word: "INDISPENSABLE", clue: "Necessary and essential" },
{ word: "ARCHITECTURE", clue: "Building design" },
{ word: "INTEGRITY", clue: "Honesty and uprightness" },
{ word: "CONQUEROR", clue: "Person who conquers" },
{ word: "POTENTIALITY", clue: "Capacity for development" },
{ word: "VERSATILITY", clue: "Adaptability" },
{ word: "SENSITIVITY", clue: "Capacity to feel" },
{ word: "CIVILIZATION", clue: "Advanced society" },
{ word: "CONSCIOUSNESS", clue: "Awareness or knowledge" },
{ word: "ARCHAEOLOGY", clue: "Study of ancient remains" },
{ word: "PRINCIPAL", clue: "Most important" },
{ word: "TRANQUILITY", clue: "Peace and calm" },
{ word: "COMPETITIVENESS", clue: "Capacity to compete" },
{ word: "COLLABORATOR", clue: "One who collaborates" },
{ word: "RECOGNITION", clue: "Admiration or gratitude" },
{ word: "INDEPENDENT", clue: "Autonomous or free" },
{ word: "UNDERSTAND", clue: "Comprehend something" },
{ word: "RESPECTABLE", clue: "Worthy of respect" },
{ word: "MYSTERIOUS", clue: "Enigmatic" },
{ word: "PROFOUNDLY", clue: "In great depth" },
{ word: "INTOLERANT", clue: "Lacking tolerance" },
{ word: "SPECIALIZED", clue: "Expert in something" },
{ word: "DISCRIMINATION", clue: "Unfair treatment" },
{ word: "ORGANIZATION", clue: "Ordered group" },
{ word: "FRAGMENTED", clue: "Divided into fragments" },
{ word: "SUBLIME", clue: "Splendid or grandiose" },
{ word: "CONTINENT", clue: "Large landmass" },
{ word: "DETERIORATE", clue: "Make something worse" },
{ word: "HETEROGENEOUS", clue: "Diverse or varied" },
{ word: "PRESTIGIOUS", clue: "Recognized and respected" },
{ word: "COMPREHENSION", clue: "Understanding" },
{ word: "INTENTIONAL", clue: "Done on purpose" },
{ word: "LIBRARY", clue: "Place of books" },
{ word: "DOMINANT", clue: "That dominates or controls" },
{ word: "INNOCENT", clue: "Not guilty" },
{ word: "ILLUMINATION", clue: "Bright light" },
{ word: "ROUNDNESS", clue: "Quality of being round" },
{ word: "PRODUCTIVE", clue: "Producing results" },
{ word: "INSTITUTION", clue: "Formal organization" },
{ word: "CONTAMINATION", clue: "Pollution or impurity" },
{ word: "FOUNDATION", clue: "Basis or principle" },
{ word: "CONTRADICTION", clue: "Opposition between ideas" },
{ word: "PRESTIGIOUS", clue: "Recognized and respected" },
{ word: "COMPREHENSION", clue: "Understanding something" },
{ word: "INSPIRATION", clue: "Creative stimulus" },
{ word: "ATMOSPHERE", clue: "Layer of gases around the Earth" },
{ word: "MYSTERIOUS", clue: "Enigmatic" },
{ word: "ORCHESTRA", clue: "Musical group" },
{ word: "DISCRIMINATION", clue: "Unfair treatment" },
{ word: "SURVIVAL", clue: "Staying alive" },
{ word: "INNOVATION", clue: "Introduction of novelties" },
{ word: "FREEDOM", clue: "Right to choose" },
{ word: "DETERMINATION", clue: "Firm decision" },
{ word: "ALCHEMY", clue: "Seeks to transform metals" },
{ word: "SPECIALTY", clue: "Area of expertise" },
{ word: "RESEARCH", clue: "Search for information" },
{ word: "CONSCIOUSLY", clue: "Deliberately" },
{ word: "DOMINANCE", clue: "Control or supremacy" },
{ word: "SPECIFIC", clue: "Defined or particular" },
{ word: "COMPILATION", clue: "Gathering of data" },
{ word: "BIOLOGY", clue: "Science of life" },
{ word: "UNIVERSITY", clue: "Educational institution" },
{ word: "ACADEMY", clue: "Educational institution" },
{ word: "CIVILIZATION", clue: "Advanced society" },
{ word: "COMPLICATED", clue: "Difficult to understand" },
{ word: "INVESTIGATOR", clue: "Person who investigates" },
{ word: "ENIGMATIC", clue: "Mysterious or enigmatic" },
{ word: "EXPERIMENTAL", clue: "Related to experiments" },
{ word: "DETERIORATION", clue: "Wear or deterioration" },
{ word: "ENRICHING", clue: "That enriches" },
{ word: "INTRODUCTION", clue: "Beginning or presentation" },
{ word: "ORGANIZATION", clue: "Ordered group" },
{ word: "DEMOCRACY", clue: "System of government" },
{ word: "OATH", clue: "Solemn promise" },
{ word: "MYSTERIOUS", clue: "Enigmatic" },
{ word: "MARVELOUS", clue: "Amazing or extraordinary" },
{ word: "INTELLIGENCE", clue: "Mental faculty" },
{ word: "BEAUTY", clue: "Beauty" },
{ word: "INFATUATION", clue: "Initial romantic feeling" },
{ word: "PREDICT", clue: "Foretell the future" },
{ word: "INFINITE", clue: "Unlimited or eternal" },
{ word: "MAGNIFICENCE", clue: "Splendor or greatness" },
{ word: "INTERACTION", clue: "Action of interacting" },
{ word: "POTENTIAL", clue: "Capacity for development" },
{ word: "DEPTH", clue: "Greatness or profundity" },
{ word: "PHENOMENAL", clue: "Extraordinary or amazing" },
{ word: "ESTABLISHMENT", clue: "Business place" },
{ word: "LITERATURE", clue: "Written work" },
{ word: "IMMENSITY", clue: "Infinite greatness" },
{ word: "PERSISTENT", clue: "Not giving up" },
{ word: "DIFFERENTIATION", clue: "Distinguishing from others" },
{ word: "SOLIDARITY", clue: "Unity and support" },
{ word: "CONTRAST", clue: "Compare differences" },
{ word: "INTERCULTURAL", clue: "Between different cultures" },
{ word: "GENEROSITY", clue: "Giving without expecting" },
{ word: "HORIZON", clue: "Line separating sky and land" },
{ word: "INCORPORATION", clue: "Inclusion" },
{ word: "IDENTIFICATION", clue: "Recognizing something or someone" },
{ word: "BIOGRAPHY", clue: "History of a person" },
{ word: "INTELLIGENT", clue: "Person with mental capacity" },
{ word: "CULTURED", clue: "Educated and refined" },
{ word: "IMAGINATION", clue: "Faculty of creating images" },
{ word: "CONFIDENTIAL", clue: "Secret or private" },
{ word: "INDISPENSABLE", clue: "Necessary and essential" },
{ word: "RUTHLESS", clue: "Unforgiving" },
{ word: "IMPACT", clue: "Effect or consequence" },
{ word: "BEAUTY", clue: "Beauty" },
{ word: "ADVENTURER", clue: "Person who seeks adventures" },
{ word: "INTROVERTED", clue: "Reserved person" },
{ word: "CONTEMPLATION", clue: "Observation with attention" },
{ word: "EXTRAORDINARY", clue: "Out of the ordinary" },
{ word: "IMAGINATIVE", clue: "Creative and imaginative" },
{ word: "DETERMINED", clue: "Decisive and focused" },
{ word: "COMPASSION", clue: "Feeling of empathy" },
{ word: "COMPREHENSIBLE", clue: "Easy to understand" },
{ word: "MASTERFUL", clue: "Master or expert" },
{ word: "TRAINING", clue: "Training" },
{ word: "RESILIENCE", clue: "Adaptation capacity" },
{ word: "OVERCOMING", clue: "Overcoming obstacles" },
{ word: "PRODUCTIVITY", clue: "Efficiency at work" },
{ word: "CONTRADICTION", clue: "Opposition between ideas" },
{ word: "INNOVATIVE", clue: "Innovative or creating novelties" },
{ word: "PERSISTENT", clue: "Persevering" },
{ word: "ILLUMINATION", clue: "Bright light" },
{ word: "RATIONALITY", clue: "Logical thinking" },
{ word: "GROWTH", clue: "Increase in size or quantity" },
{ word: "STRATEGY", clue: "Planning" },
{ word: "CONVICTION", clue: "Firm belief" },
{ word: "DETERMINING", clue: "Decisive or influential" },
{ word: "PREDICTION", clue: "Future prediction" },
{ word: "SINCERITY", clue: "Honesty and truth" },
{ word: "DISTINGUISHED", clue: "Elegant and respected" },
{ word: "PLURALITY", clue: "Variety or diversity" },
{ word: "FRATERNITY", clue: "Unity and brotherhood" },
{ word: "INTENSITY", clue: "Degree of strength" },
{ word: "BEAUTIFULLY", clue: "In a beautiful manner" },
{ word: "INTELLIGENCE", clue: "Mental faculty" },
{ word: "POSITIVITY", clue: "Positive thinking" },
{ word: "WISDOM", clue: "Deep knowledge" },
{ word: "EFFERVESCENCE", clue: "Agitation or excitement" },
{ word: "FUNDAMENTAL", clue: "Basic or essential" },
{ word: "COMPETITION", clue: "Rivalry" },
{ word: "FRIENDSHIP", clue: "Relationship of friends" },
{ word: "MARVELOUS", clue: "Amazing or impressive" },
{ word: "INDOMITABLE", clue: "Cannot be tamed" },
{ word: "MAGISTRATE", clue: "Person in a judicial position" },
{ word: "EXEMPLARY", clue: "Serving as an example" },
{ word: "PERSISTENCE", clue: "Resistance to adversity" },
{ word: "INNOVATION", clue: "Creativity" },
{ word: "COOPERATION", clue: "Teamwork" },
{ word: "HONORABLE", clue: "Worthy of honor" },
{ word: "RESPONSIBLE", clue: "Fulfilling one's duties" },
{ word: "TRANSCENDENT", clue: "Of great importance" },
{ word: "INVOLVEMENT", clue: "Active participation" },
{ word: "CONTRADICTION", clue: "Incoherence" },
{ word: "ENLIGHTENED", clue: "Who has reached enlightenment" },
{ word: "MIRACULOUS", clue: "That seems like a miracle" },
{ word: "LEGACY", clue: "Inheritance or teaching" },
{ word: "RELEVANCE", clue: "Importance" },
{ word: "OUTSTANDING", clue: "Excellent" },
{ word: "EXPERIMENTAL", clue: "Related to experiments" },
{ word: "MARVEL", clue: "Admirable thing" },
{ word: "INDISPENSABLE", clue: "Necessary and essential" },
{ word: "ARCHITECTURE", clue: "Building design" },
{ word: "INTEGRITY", clue: "Honesty and rectitude" },
{ word: "CONQUEROR", clue: "Person who conquers" },
{ word: "POTENTIALITY", clue: "Capacity for development" },
{ word: "VERSATILITY", clue: "Adaptability" },
{ word: "SENSIBILITY", clue: "Capacity to feel" },
{ word: "CIVILIZATION", clue: "Advanced society" },
{ word: "CONSCIENCE", clue: "Consciousness or knowledge" },
{ word: "ARCHAEOLOGY", clue: "Study of ancient remains" },
{ word: "PRINCIPAL", clue: "More important" },
{ word: "TRANQUILITY", clue: "Peace and calm" },
{ word: "COMPETITIVENESS", clue: "Ability to compete" },
{ word: "COLLABORATOR", clue: "One who collaborates" },
{ word: "RECOGNITION", clue: "Admiration or acknowledgment" },
{ word: "INDEPENDENT", clue: "Autonomous or free" },
{ word: "COMPREHEND", clue: "Understand something" },
{ word: "RESPECTABLE", clue: "Worthy of respect" },
{ word: "MYSTERIOUS", clue: "Enigmatic" },
{ word: "PROFOUNDLY", clue: "In great depth" },
{ word: "INTOLERANT", clue: "Lack of tolerance" },
{ word: "SPECIALIZED", clue: "Expert in something" },
{ word: "DISCRIMINATION", clue: "Unfair treatment" },
{ word: "ORGANIZATION", clue: "Ordered group" },
{ word: "FRAGMENTED", clue: "Divided into fragments" },
{ word: "SUBLIME", clue: "Splendid or grand" },
{ word: "CONTINENT", clue: "Large landmass" },
{ word: "DETERIORATE", clue: "To make something worse" },
{ word: "HETEROGENEOUS", clue: "Diverse or varied" },
{ word: "PRESTIGIOUS", clue: "Recognized and respected" },
{ word: "COMPREHENSION", clue: "Understanding" },
{ word: "INTENTIONAL", clue: "Done on purpose" },
{ word: "LIBRARY", clue: "Place of books" },
{ word: "DOMINANT", clue: "That dominates or controls" },
{ word: "INNOCENT", clue: "Not guilty" },
{ word: "ILLUMINATION", clue: "Bright light" },
{ word: "ROUNDNESS", clue: "Quality of being round" },
{ word: "PRODUCTIVE", clue: "That produces results" },
{ word: "INSTITUTION", clue: "Formal organization" },
{ word: "CONTAMINATION", clue: "Pollution or impurity" },
{ word: "FOUNDATION", clue: "Basis or principle" },
{ word: "CONTRADICTION", clue: "Opposition between ideas" },
{ word: "PRESTIGIOUS", clue: "Recognized and respected" },
{ word: "COMPREHENSION", clue: "Understanding something" },
{ word: "INSPIRATION", clue: "Creative stimulus" },
{ word: "ATMOSPHERE", clue: "Layer of gases around the Earth" },
{ word: "MYSTERIOUS", clue: "Enigmatic" },
{ word: "ORCHESTRA", clue: "Musical group" },
{ word: "DISCRIMINATION", clue: "Unfair treatment" },
{ word: "SURVIVAL", clue: "Remaining alive" },
{ word: "INNOVATION", clue: "Introduction of novelties" },
{ word: "FREEDOM", clue: "Right to choose" },
{ word: "DETERMINATION", clue: "Firm decision" },
{ word: "ALCHEMY", clue: "Seeks to transform metals" },
{ word: "SPECIALTY", clue: "Area of expertise" },
{ word: "INVESTIGATION", clue: "Search for information" },
{ word: "CONSCIOUSLY", clue: "Deliberately" },
{ word: "DOMINANCE", clue: "Control or supremacy" },
{ word: "DETERMINED", clue: "Specific or defined" },
{ word: "COMPILATION", clue: "Gathering of data" },
{ word: "BIOLOGY", clue: "Science of life" },
{ word: "UNIVERSITY", clue: "Educational institution" },
{ word: "ACADEMY", clue: "Educational institution" },
{ word: "CIVILIZATION", clue: "Advanced society" },
{ word: "COMPLICATED", clue: "Difficult to understand" },
{ word: "INVESTIGATOR", clue: "Person who investigates" },
{ word: "ENIGMATIC", clue: "Mysterious or enigmatic" },
{ word: "EXPERIMENTAL", clue: "Related to experiments" },
{ word: "DETERIORATION", clue: "Wear or deterioration" },
{ word: "ENRICHING", clue: "That enriches" },
{ word: "INTRODUCTION", clue: "Beginning or presentation" },
{ word: "ORGANIZATION", clue: "Ordered group" },
{ word: "DEMOCRACY", clue: "System of government" },
{ word: "OATH", clue: "Solemn promise" },
{ word: "MYSTERIOUS", clue: "Enigmatic" },
{ word: "PRODIGIOUS", clue: "Amazing or extraordinary" },
{ word: "INTELLIGENCE", clue: "Mental faculty" },
{ palabra: "HERMOSURA", pista: "Belleza" },
        { palabra: "ENAMORAMIENTO", pista: "Sentimiento amoroso inicial" },
        { palabra: "PREDECIR", pista: "Adivinar el futuro" },
        { palabra: "INFINITO", pista: "Ilimitado o eterno" },
        { palabra: "MAGNIFICENCIA", pista: "Esplendor o grandeza" },
        { palabra: "INTERACCION", pista: "Acción de interactuar" },
        { palabra: "POTENCIAL", pista: "Capacidad para desarrollarse" },
        { palabra: "PROFUNDIDAD", pista: "Grandeza o profundidad" },
        { palabra: "FENOMENAL", pista: "Extraordinario o asombroso" },
        { palabra: "ESTABLECIMIENTO", pista: "Lugar de negocio" },
        { palabra: "LITERATURA", pista: "Obra escrita" },
        { palabra: "INMENSIDAD", pista: "Grandeza infinita" },
        { palabra: "PERSISTENTE", pista: "Que no se rinde" },
        { palabra: "DIFERENCIACION", pista: "Distinguir de otros" },
        { palabra: "SOLIDARIDAD", pista: "Unión y apoyo" },
        { palabra: "CONTRASTAR", pista: "Comparar diferencias" },
        { palabra: "INTERCULTURAL", pista: "Entre diferentes culturas" },
        { palabra: "GENEROSIDAD", pista: "Dar sin esperar" },
        { palabra: "HORIZONTE", pista: "Línea que separa cielo y tierra" },
        { palabra: "INCORPORACION", pista: "Inclusión" },
        { palabra: "IDENTIFICACION", pista: "Reconocer algo o alguien" },
        { palabra: "BIOGRAFIA", pista: "Historia de una persona" },
        { palabra: "INTELIGENTE", pista: "Persona con capacidad mental" },
        { palabra: "CULTIVADO", pista: "Educado y refinado" },
        { palabra: "IMAGINACION", pista: "Facultad de crear imágenes" },
        { palabra: "CONFIDENCIAL", pista: "Secreto o privado" },
        { palabra: "IMPRESCINDIBLE", pista: "Necesario e indispensable" },
        { palabra: "IMPLACABLE", pista: "Que no perdona" },
        { palabra: "REPERCUSION", pista: "Impacto o consecuencia" },
        { palabra: "HERMOSURA", pista: "Belleza" },
        { palabra: "AVENTURERO", pista: "Persona que busca aventuras" },
        { palabra: "INTROVERTIDO", pista: "Persona reservada" },
        { palabra: "CONTEMPLACION", pista: "Observación con atención" },
        { palabra: "EXTRAORDINARIO", pista: "Fuera de lo común" },
        { palabra: "IMAGINATIVO", pista: "Creativo y fantasioso" },
        { palabra: "DETERMINADO", pista: "Decidido y enfocado" },
        { palabra: "COMPASION", pista: "Sentimiento de empatía" },
        { palabra: "COMPRENSIBLE", pista: "Fácil de entender" },
        { palabra: "MAGISTRAL", pista: "Maestro o experto" },
        { palabra: "CAPACITACION", pista: "Entrenamiento" },
        { palabra: "RESILIENCIA", pista: "Capacidad de adaptación" },
        { palabra: "SUPERACION", pista: "Vencer obstáculos" },
        { palabra: "PRODUCTIVIDAD", pista: "Eficiencia en el trabajo" },
        { palabra: "CONTRADICCION", pista: "Oposición entre ideas" },
        { palabra: "INNOVADOR", pista: "Que innova o crea novedades" },
        { palabra: "PERSEVERANTE", pista: "Que persevera" },
        { palabra: "ILUMINACION", pista: "Luz brillante" },
        { palabra: "RACIONALIDAD", pista: "Pensamiento lógico" },
        { palabra: "CRECIMIENTO", pista: "Aumento en tamaño o cantidad" },
        { palabra: "ESTRATEGIA", pista: "Planificación" },
        { palabra: "CONVICCION", pista: "Creencia firme" },
        { palabra: "DETERMINANTE", pista: "Que decide o influye" },
        { palabra: "PREDICCION", pista: "Adivinación del futuro" },
        { palabra: "SINCERIDAD", pista: "Honestidad y verdad" },
        { palabra: "DISTINGUIDO", pista: "Elegante y respetado" },
        { palabra: "PLURALIDAD", pista: "Variedad o diversidad" },
        { palabra: "FRATERNIDAD", pista: "Unión y hermandad" },
        { palabra: "INTENSIDAD", pista: "Grado de fuerza" },
        { palabra: "HERMOSAMENTE", pista: "De manera hermosa" },
        { palabra: "INTELIGENCIA", pista: "Facultad mental" },
        { palabra: "POSITIVIDAD", pista: "Pensamiento positivo" },
        { palabra: "SABIDURIA", pista: "Conocimiento profundo" },
        { palabra: "EFERVESCENCIA", pista: "Agitación o excitación" },
        { palabra: "FUNDAMENTAL", pista: "Básico o esencial" },
        { palabra: "COMPETENCIA", pista: "Rivalidad" },
        { palabra: "AMISTAD", pista: "Relación de amigos" },
        { palabra: "MARAVILLOSO", pista: "Asombroso o impresionante" },
        { palabra: "INDOMABLE", pista: "Que no se puede domar" },
        { palabra: "MAGISTRADO", pista: "Persona en posición judicial" },
        { palabra: "EJEMPLAR", pista: "Que sirve de ejemplo" },
        { palabra: "PERSISTENCIA", pista: "Resistencia a la adversidad" },
        { palabra: "INNOVACION", pista: "Creatividad" },
        { palabra: "COOPERACION", pista: "Trabajo en equipo" },
        { palabra: "HONORABLE", pista: "Digno de honor" },
        { palabra: "RESPONSABLE", pista: "Cumplidor de sus deberes" },
        { palabra: "TRASCENDENTE", pista: "De gran importancia" },
        { palabra: "INVOLUCRAMIENTO", pista: "Participación activa" },
        { palabra: "CONTRADICCION", pista: "Incoherencia" },
        { palabra: "ILUMINADO", pista: "Que ha alcanzado la iluminación" },
        { palabra: "MILAGROSO", pista: "Que parece un milagro" },
        { palabra: "LEGADO", pista: "Herencia o enseñanza" },
        { palabra: "RELEVANCIA", pista: "Importancia" },
        { palabra: "DESTACADO", pista: "Sobresaliente" },
        { palabra: "EXPERIMENTAL", pista: "Relativo a experimentos" },
        { palabra: "MARAVILLA", pista: "Cosa admirable" },
        { palabra: "INDISPENSABLE", pista: "Necesario e imprescindible" },
        { palabra: "ARQUITECTURA", pista: "Diseño de edificios" },
        { palabra: "INTEGRIDAD", pista: "Honestidad y rectitud" },
        { palabra: "CONQUISTADOR", pista: "Persona que conquista" },
        { palabra: "POTENCIALIDAD", pista: "Capacidad de desarrollo" },
        { palabra: "VERSATILIDAD", pista: "Adaptabilidad" },
        { palabra: "SENSIBILIDAD", pista: "Capacidad de sentir" },
        { palabra: "CIVILIZACION", pista: "Sociedad avanzada" },  
];

function selectRandomWord() {
    const randomIndex = Math.floor(Math.random() * words.length);
    return words[randomIndex];
}

let selectedWord = selectRandomWord();
let wordToGuess = selectedWord.word;
let hint = selectedWord.clue;

// Initialize variables
let guesses = 0;
let mistakes = 0;
let guessedWord = "";

// Get DOM elements
const typeInput = document.querySelector(".type-input");
const wordDisplay = document.querySelector(".word");
const guessDisplay = document.querySelector(".guess span");
const mistakesDisplay = document.querySelector(".wrong span");
const hintDisplay = document.querySelector(".hint span");
const resetButton = document.querySelector(".reset");
const showHintButton = document.querySelector(".showhint");

// Event to show a hint related to the word
showHintButton.addEventListener("click", () => {
    hintDisplay.textContent = "Hint: " + hint;
});

// Initialize the hidden word
for (let i = 0; i < wordToGuess.length; i++) {
    guessedWord += "_";
}

// Display the hidden word on the screen
wordDisplay.textContent = guessedWord;

// Event to guess letters
typeInput.addEventListener("input", () => {
    const letter = typeInput.value.toUpperCase();
    typeInput.value = "";

    if (wordToGuess.includes(letter)) {
        // The letter is in the word
        for (let i = 0; i < wordToGuess.length; i++) {
            if (wordToGuess[i] === letter) {
                guessedWord = guessedWord.substr(0, i) + letter + guessedWord.substr(i + 1);
            }
        }
    } else {
        // The letter is not in the word
        mistakes++;
    }

    guesses++;
    wordDisplay.textContent = guessedWord;
    guessDisplay.textContent = guesses;
    mistakesDisplay.textContent = mistakes;

    // Check if the complete word has been guessed
    if (guessedWord === wordToGuess) {
        alert("You've won! The word is: " + wordToGuess);
    } else if (mistakes >= 14) {
        alert("You have lost! The word was: " + wordToGuess);
    }
});

resetButton.addEventListener("click", () => {
    // Select a new random word and its hint
    selectedWord = selectRandomWord();
    wordToGuess = selectedWord.word;
    hint = selectedWord.clue;

    guesses = 0;
    mistakes = 0;
    guessedWord = "";
    for (let i = 0; i < wordToGuess.length; i++) {
        guessedWord += "_";
    }
    wordDisplay.textContent = guessedWord;
    guessDisplay.textContent = guesses;
    mistakesDisplay.textContent = mistakes;
    hintDisplay.textContent = ""; // Clear the displayed hint
});
